[book]
authors = ["Abanobbb"]
language = "en"
multilingual = false
src = "src"
title = " "

[output.html]
additional-js = ["custom.js"]
base-url =  "https://abanoubnashaat.xyz/"
site-url = "/mdBook/"

[output.html.search]
enable = true




