[book]
authors = ["Abanobbb"]
language = "en"
multilingual = false
src = "src"
title = " "

[output.html]
additional-js = ["custom.js"]
base-url = "/"
site-url = "/"

[output.html.search]
enable = true



